// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gzNoOwF8P5FxA65ufF9Zh57fsuDwYRU',
    appId: '1:788910457317:web:8ca9cfd2e5e9ad9010af0c',
    messagingSenderId: '788910457317',
    projectId: 'semsark-529c0',
    authDomain: 'semsark-529c0.firebaseapp.com',
    databaseURL: 'https://semsark-529c0-default-rtdb.firebaseio.com',
    storageBucket: 'semsark-529c0.appspot.com',
    measurementId: 'G-L876XYDSSH',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQk_gpB_exnXm0xUftlMmE2fWn0XQb88',
    appId: '1:788910457317:android:4c1926d3a6d4e07410af0c',
    messagingSenderId: '788910457317',
    projectId: 'semsark-529c0',
    databaseURL: 'https://semsark-529c0-default-rtdb.firebaseio.com',
    storageBucket: 'semsark-529c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0XyAJfmI8cjsFdjfyoUYEtUYHA-3atb4',
    appId: '1:788910457317:ios:ab68a17d99446bb510af0c',
    messagingSenderId: '788910457317',
    projectId: 'semsark-529c0',
    databaseURL: 'https://semsark-529c0-default-rtdb.firebaseio.com',
    storageBucket: 'semsark-529c0.appspot.com',
    iosClientId: '788910457317-rmg81muo10irrrd0ggecdiesjlh9cc1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.semsark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0XyAJfmI8cjsFdjfyoUYEtUYHA-3atb4',
    appId: '1:788910457317:ios:ab68a17d99446bb510af0c',
    messagingSenderId: '788910457317',
    projectId: 'semsark-529c0',
    databaseURL: 'https://semsark-529c0-default-rtdb.firebaseio.com',
    storageBucket: 'semsark-529c0.appspot.com',
    iosClientId: '788910457317-rmg81muo10irrrd0ggecdiesjlh9cc1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.semsark',
  );
}
